2.0.1
Fixed file / directory sort order issue in Linux

diff --git a/ssasm b/ssasm
--- a/ssasm
+++ b/ssasm
@@ -4,9 +4,9 @@
 ## This utility will scan through subdirectories looking for database scripts (fragments) to assemble into a 
 ## master build script. The master script will be built with appropriate headers for formatting/readability purposes 
 ## (editable in ssasm-header.txt) and will incorporate:
-## 	* The name of script where the fragment originated
-##	* Pause points (editable in the ssasm-footer.txt file) between each script fragment for review purposes 
-## 	* Spool commmands to output each fragment executed in /tmp/ss_{SCHEMA_NAME}{N}.txt (N starting at 1) for review, etc.
+##      * The name of script where the fragment originated
+##      * Pause points (editable in the ssasm-footer.txt file) between each script fragment for review purposes 
+##      * Spool commmands to output each fragment executed in /tmp/ss_{SCHEMA_NAME}{N}.txt (N starting at 1) for review, etc.
 ##
 ## The latest availble version can be found at: https://github.com/cryptoknows/ssasm
 ##
@@ -20,12 +20,12 @@
 ##
 ## Options:
 ##
-## -d	- database_type - The DB / client platform the assembled script will be executed against. Accepted values:
-##  			  oracle (default), mysql
+## -d   - database_type - The DB / client platform the assembled script will be executed against. Accepted values:
+##                        oracle (default), mysql
 ##
-## -s 	- schema_name	- The name of schema (embedded in the folder names) to process. Case sensitive
+## -s   - schema_name   - The name of schema (embedded in the folder names) to process. Case sensitive
 ##
-## -f	- file_type	- The file type (suffix) to assemble (default is ".sql" (minus the quotes)). Case insensitive
+## -f   - file_type     - The file type (suffix) to assemble (default is ".sql" (minus the quotes)). Case insensitive
 ##
 ## ---------------------------------------------------------------------------------------------------------------------
 ##
@@ -35,8 +35,8 @@
 ## 
 ## For example:
 ##
-## 2016-01-02-MY_SCHEMA-			-- No secondary comment added
-## 2016-01-05-MY_SCHEMA-Modified_Version 	-- Comments added
+## 2016-01-02-MY_SCHEMA-                        -- No secondary comment added
+## 2016-01-05-MY_SCHEMA-Modified_Version        -- Comments added
 ##
 ## NOTES:
 ##
@@ -66,7 +66,7 @@
 ##
 ##
 
-VERSION=2.0.0
+VERSION=2.0.1
 CTR=1
 INTERNAL_PATH=`dirname $0`
 DATABASE="oracle"
@@ -75,18 +75,18 @@ FTYPE=""
 while getopts "d:s:f:" opt; do
   case $opt in
     s) SCHEMA=$OPTARG
- 	;; 
+        ;; 
     f) FTYPE=$OPTARG
- 	;; 
+        ;; 
     d)
       if [ "$OPTARG" != "oracle" ] && [ "$OPTARG" != "mysql" ]
       then
-	echo "Sorry, '${OPTARG}' isn't a recognized database target!"
-	exit 1
+        echo "Sorry, '${OPTARG}' isn't a recognized database target!"
+        exit 1
       else 
-	DATABASE=$OPTARG
-      fi	
-	;;
+        DATABASE=$OPTARG
+      fi
+        ;;
     \?)
       echo "Invalid option: -$OPTARG" >&2
       exit 1
@@ -102,9 +102,9 @@ shift $((OPTIND-1))
 
 if [ "$1" ] 
 then
-	SOURCE_DIR="${1}"
+        SOURCE_DIR="${1}"
 else
-	SOURCE_DIR="."
+        SOURCE_DIR="."
 fi
 
 ## ------------------------------------------------------------------------------------------
@@ -118,35 +118,35 @@ echo "Refer to the SSAsm source directory for more information."
 echo
 if [ ${SCHEMA} ]
 then
-	echo "Schema Specified: 	'${SCHEMA}'"
+        echo "Schema Specified:         '${SCHEMA}'"
 else
-	echo -n ">>Enter a schema name to build: "
-	read SCHEMA
-	if [ ! ${SCHEMA} ]
-	then
-		echo "*** ERROR! *** You must provide a schema name!"
-		exit
-	fi
-	echo
-	echo
+        echo -n ">>Enter a schema name to build: "
+        read SCHEMA
+        if [ ! ${SCHEMA} ]
+        then
+                echo "*** ERROR! *** You must provide a schema name!"
+                exit
+        fi
+        echo
+        echo
 fi
 
 
-echo "Target DB Platform: 	'${DATABASE}'"
+echo "Target DB Platform:       '${DATABASE}'"
 if [ ${FTYPE} ] 
 then
-	echo "Filetype Specified:	'${FTYPE}'"
+        echo "Filetype Specified:       '${FTYPE}'"
 else
-	echo; echo; echo;
-	echo -n ">>Enter a filetype to integrate (case insensitive): [.sql]: "
-	read FTYPE
-	if [ ! ${FTYPE} ]
-	then
-        	FTYPE=".sql"
-	fi
-	echo; echo;
+        echo; echo; echo;
+        echo -n ">>Enter a filetype to integrate (case insensitive): [.sql]: "
+        read FTYPE
+        if [ ! ${FTYPE} ]
+        then
+                FTYPE=".sql"
+        fi
+        echo; echo;
 fi
-echo "Path to Process:	'${SOURCE_DIR}'"
+echo "Path to Process:  '${SOURCE_DIR}'"
 echo ""
 echo ""
 OFILE="build_${SCHEMA}${FTYPE}"
@@ -159,85 +159,85 @@ echo -n ">>Proceed? [N]: "
 read READY
 if [ "$READY" = "Y" ] || [ "$READY" = "y" ]
 then
-	tput clear
-	echo ""
-	echo "### GENERATING..."
-	echo "###"
-	echo "-- The following script was generated by the SQL Script Assembler (SSAsm) V${VERSION}" >$OFILE
-	echo "-- Get your copy today at https://github.com/cryptoknows/ssasm" >>$OFILE
-	echo "--">>$OFILE
-	echo "--">>$OFILE
+        tput clear
+        echo ""
+        echo "### GENERATING..."
+        echo "###"
+        echo "-- The following script was generated by the SQL Script Assembler (SSAsm) V${VERSION}" >$OFILE
+        echo "-- Get your copy today at https://github.com/cryptoknows/ssasm" >>$OFILE
+        echo "--">>$OFILE
+        echo "--">>$OFILE
 
-	case ${DATABASE} in
+        case ${DATABASE} in
                 oracle)
-			echo "prompt" >>$OFILE
-			echo "prompt" >>$OFILE
-			echo "prompt PRESS ENTER TO BEGIN THE $SCHEMA SCRIPT SCRIPT EXECUTION">>$OFILE
-			echo "accept abc">>$OFILE
-		;;
+                        echo "prompt" >>$OFILE
+                        echo "prompt" >>$OFILE
+                        echo "prompt PRESS ENTER TO BEGIN THE $SCHEMA SCRIPT SCRIPT EXECUTION">>$OFILE
+                        echo "accept abc">>$OFILE
+                ;;
                 mysql)
-			echo "\! echo" >>$OFILE
-			echo "\! echo" >>$OFILE
-			echo "\! echo 'PRESS ENTER TO BEGIN THE $SCHEMA SCRIPT SCRIPT EXECUTION'">>$OFILE
-			echo "\! read abc">>$OFILE
+                        echo "\! echo" >>$OFILE
+                        echo "\! echo" >>$OFILE
+                        echo "\! echo 'PRESS ENTER TO BEGIN THE $SCHEMA SCRIPT SCRIPT EXECUTION'">>$OFILE
+                        echo "\! read abc">>$OFILE
                 ;;
         esac
-	
+
 
 find $SOURCE_DIR -name "Rejected" -prune -o -print | grep "\-${SCHEMA}\-" | grep -i ${FTYPE} >/tmp/rrrun.txt
 DONE="no"
 cat /tmp/rrrun.txt | while read LINE
 do
-	echo "### PROCESSING: $LINE"
-	case ${DATABASE} in
-		oracle)
-			echo "set echo off" >>$OFILE
-			echo " ">>$OFILE
-		;;
-	esac
-
-	cat ${INTERNAL_PATH}/ssasm-header-${DATABASE}.txt >>$OFILE
-	case ${DATABASE} in
-		oracle)
-			echo "spool /tmp/ss_${SCHEMA}${CTR}.txt">>$OFILE
-		;;
-		mysql)
-			echo "tee /tmp/ss_${SCHEMA}${CTR}.txt">>$OFILE
-		;;
-	esac
-	CTR=$(($CTR+1))
-	
-	case ${DATABASE} in
+        echo "### PROCESSING: $LINE"
+        case ${DATABASE} in
                 oracle)
-			echo "prompt ------------------------------------------------------------------------------------------" >>$OFILE
-			echo " ">>$OFILE
-			echo "prompt -- CONTENTS OF $LINE EXECUTING BELOW" >>$OFILE
-			echo " ">>$OFILE
-			echo "prompt  ">>$OFILE
-			echo "prompt  ">>$OFILE
-			echo "prompt  ">>$OFILE
-			echo "prompt  ">>$OFILE
-			echo "prompt  ">>$OFILE
-			echo "set echo on" >>$OFILE
+                        echo "set echo off" >>$OFILE
+                        echo " ">>$OFILE
                 ;;
-                mysql)
-			echo "\! echo ' ------------------------------------------------------------------------------------------'" >>$OFILE
-			echo "\! echo ">>$OFILE
-			echo "\! echo 'CONTENTS OF $LINE EXECUTING BELOW'" >>$OFILE
-			echo " ">>$OFILE
-			echo "\! echo ">>$OFILE
-			echo "\! echo ">>$OFILE
-			echo "\! echo ">>$OFILE
-			echo "\! echo ">>$OFILE
-			echo "\! echo ">>$OFILE
-		;;
         esac
 
-	## When catting file, make sure to get rid of DOS \r's along the way
-	cat $LINE | tr -d '\r' >>$OFILE
-	echo " ">>$OFILE
+        cat ${INTERNAL_PATH}/ssasm-header-${DATABASE}.txt >>$OFILE
+        case ${DATABASE} in
+                oracle)
+                        echo "spool /tmp/ss_${SCHEMA}${CTR}.txt">>$OFILE
+                ;;
+                mysql)
+                        echo "tee /tmp/ss_${SCHEMA}${CTR}.txt">>$OFILE
+                ;;
+        esac
+        CTR=$(($CTR+1))
 
-	case ${DATABASE} in
+        case ${DATABASE} in
+                oracle)
+                        echo "prompt ------------------------------------------------------------------------------------------" >>$OFILE
+                        echo " ">>$OFILE
+                        echo "prompt -- CONTENTS OF $LINE EXECUTING BELOW" >>$OFILE
+                        echo " ">>$OFILE
+                        echo "prompt  ">>$OFILE
+                        echo "prompt  ">>$OFILE
+                        echo "prompt  ">>$OFILE
+                        echo "prompt  ">>$OFILE
+                        echo "prompt  ">>$OFILE
+                        echo "set echo on" >>$OFILE
+                ;;
+                mysql)
+                        echo "\! echo ' ------------------------------------------------------------------------------------------'" >>$OFILE
+                        echo "\! echo ">>$OFILE
+                        echo "\! echo 'CONTENTS OF $LINE EXECUTING BELOW'" >>$OFILE
+                        echo " ">>$OFILE
+                        echo "\! echo ">>$OFILE
+                        echo "\! echo ">>$OFILE
+                        echo "\! echo ">>$OFILE
+                        echo "\! echo ">>$OFILE
+                        echo "\! echo ">>$OFILE
+                ;;
+        esac
+
+        ## When catting file, make sure to get rid of DOS \r's along the way
+        cat $LINE | tr -d '\r' >>$OFILE
+        echo " ">>$OFILE
+
+        case ${DATABASE} in
                 oracle)
                         echo "spool off">>$OFILE
                 ;;
@@ -246,32 +246,31 @@ do
                 ;;
         esac
 
-	cat ${INTERNAL_PATH}/ssasm-footer-${DATABASE}.txt >>$OFILE
+        cat ${INTERNAL_PATH}/ssasm-footer-${DATABASE}.txt >>$OFILE
 done
 
-	        case ${DATABASE} in
+                case ${DATABASE} in
                 oracle)
-			echo "prompt  ">>$OFILE
-			echo "prompt  ">>$OFILE
-			echo "prompt  ">>$OFILE
-			echo "prompt  ">>$OFILE
-			echo "prompt  ">>$OFILE
-			echo "prompt -- END OF RELEASE SCRIPT REACHED. CONGRATULATIONS!" >>$OFILE
+                        echo "prompt  ">>$OFILE
+                        echo "prompt  ">>$OFILE
+                        echo "prompt  ">>$OFILE
+                        echo "prompt  ">>$OFILE
+                        echo "prompt  ">>$OFILE
+                        echo "prompt -- END OF RELEASE SCRIPT REACHED. CONGRATULATIONS!" >>$OFILE
                 ;;
                 mysql)
-			echo "\! echo ">>$OFILE
-			echo "\! echo ">>$OFILE
-			echo "\! echo ">>$OFILE
-			echo "\! echo ">>$OFILE
-			echo "\! echo ">>$OFILE
-			echo "\! echo 'END OF RELEASE SCRIPT REACHED. CONGRATULATIONS!'" >>$OFILE
+                        echo "\! echo ">>$OFILE
+                        echo "\! echo ">>$OFILE
+                        echo "\! echo ">>$OFILE
+                        echo "\! echo ">>$OFILE
+                        echo "\! echo ">>$OFILE
+                        echo "\! echo 'END OF RELEASE SCRIPT REACHED. CONGRATULATIONS!'" >>$OFILE
                 ;;
         esac
 
 
 
-	echo ""	
-	echo "Script assembly complete. "
-	echo "Output saved to: `pwd`/${OFILE}"	
-fi 
-
+        echo ""
+        echo "Script assembly complete. "
+        echo "Output saved to: `pwd`/${OFILE}"
+fi
